### ISSUE TITLE
Need help !

### ISSUE THREAD

**Issue by belahssen** [mmoya/pkg-thc-ipv6#3]
Guys this i have a problem
what should i configure for the flood
cauze i have a windows 7 machine so when i run flood_router26 ens33 
===> nothing happend to the windows machine
# what should i configure to run well with me ?

**Comment by mmoya** [comment]
Belahssen, I'm not longer maintaining the Debian package for thc-ipv6, it was migrated to https://anonscm.debian.org/git/pkg-security/thc-ipv6.git. The upstream repo is located at https://github.com/vanhauser-thc/thc-ipv6.

Regarding your question, I suggest you to capture network traffic to at least confirm the flooding is taking place.
